"""Crear modelo Tarea

Revision ID: d4ba3f3d2d61
Revises: 6c1eea0203f0
Create Date: 2025-10-27 22:31:56.045130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4ba3f3d2d61'
down_revision: Union[str, None] = '6c1eea0203f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completada', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('completado')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completado', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('completada')

    # ### end Alembic commands ###
